'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Invoicing

    '''<summary>
    '''grdInsertInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdInsertInvoice As Global.System.Web.UI.WebControls.DetailsView

    '''<summary>
    '''hdnValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnValueEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnValueEdit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdEditInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdEditInvoice As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlInvoice As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlClientID As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlSupplier As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlAuditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlAuditor As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlEditSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlEditSupplier As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlEditAuditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlEditAuditor As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlBillingTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlBillingTypes As Global.System.Web.UI.WebControls.SqlDataSource
End Class
