'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class timetrack

    '''<summary>
    '''gridTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTimesheet As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''sQTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sQTimesheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sQEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sQEmployee As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sQProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sQProject As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sQTasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sQTasks As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDSEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDSEmployee As Global.System.Web.UI.WebControls.SqlDataSource
End Class
